In [3]:
import numpy as np

# ndarray - N-dimensional array object

- All of the elements must be the same type

## Característiques: dimension, shape, dtype

In [7]:
# De llista a array

llista = [[[1, 2, 3, 4], [5.4, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]

arr = np.array(llista)

print(arr) # tots seran floats perquè n'hi havia un i tots han de tenir el mateix type

print(arr.ndim) # 3 dimensions. Profunditat, files, columnes
print(arr.shape) # 2 matrius Profunditat, 2 files, 4 columnes
print(arr.dtype) # són floats

# Forçar el type dels elements
arr2 = np.array(llista, dtype=np.int64) # Els decimals els trunca
print(arr2)

# Convertir el tipus d'un array. Sempre crea un NOU array, una còpia de l'anterior canviant el tipus.
arr22 = arr.astype(np.int64) # De arr type float a arr22 type int
print(arr22)

[[[ 1.   2.   3.   4. ]
  [ 5.4  6.   7.   8. ]]

 [[ 9.  10.  11.  12. ]
  [13.  14.  15.  16. ]]]
3
(2, 2, 4)
float64
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


## Creació

In [23]:
# Crear array amb valors random seguint distribució normal mean 0, standard deviation 1.
data = np.random.randn(2,3)
print(data)
# np.random.binomial
# np.random.uniform
# np.random.randint ...

# Crear array de zeros o uns
zeros = np.zeros(3) # 1 fila, 3 columnes
print(zeros)
uns = np.ones((1,2))
print(uns)

# Crear array amb valors qualsevol, sense inicialitzar. De vegades són zeros, a vegades no.
garbage = np.empty((2,1,3))
print(garbage)

# Crear array similar a funció range
num = np.arange(15)
print(num)
num2 = np.arange(8).reshape((4, 2)) # del 0 al 7 en 4 files i 2 columnes.
print(num2)

identitat = np.identity(3) # matriu identitat 3x3
print(identitat)

[[-0.05017251 -0.25432579  0.35146367]
 [ 0.41811518 -0.45651343  1.42206112]]
[0. 0. 0.]
[[1. 1.]]
[[[0.05017251 0.25432579 0.35146367]]

 [[0.41811518 0.45651343 1.42206112]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Operacions amb arrays (vectorization)

- Com operacions amb matrius.
- Cal que tinguin la mateixa dimensió.
- Cuando operamos entre arrays con dimensiones diferentes, siempre y cuando se cumplan ciertas restricciones en tamaños de filas y/o columnas, lo que se produce es un «broadcasting» (o difusión) de los valores.

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 1, 9], [10, 11, 12]])

print(arr + arr2)
print(arr - arr)
print(arr ** 2)
print(1/arr)
print(arr2 > arr)

[[ 8  3 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ True False  True]
 [ True  True  True]]


In [54]:
# broadcasting

m23 = np.array([[9, 8, 1], [7, 6, 7]])
m13 = np.array([2, 3, 6])
m21 = np.array([[1], [6]])

print(m23 + m13) # Suma la fila de m13 a les dues files de m23
print(m23 + m21) # Suma la columna de m21 a les 3 columnes de m23

[[11 11  7]
 [ 9  9 13]]
[[10  9  2]
 [13 12 13]]


## Indexing and slicing

- Array slices are VIEWS on the original array. This means that data is not copied, and ANY MODIFICATIONS TO THE VIEW WILL BE REFLECTED IN THE SOURCE ARRAY.

In [79]:
arr = np.arange(10)
print("l'array és:", arr)

# Seleccionar un element
print("l'element 2:", arr[2])

# Seleccionar un slice
print("secció de l'array:", arr[5:8]) # l'element 5, 6 i 7, començant a contar per 0.

# Modificar elements
arr_slice = arr[5:8]
arr_slice[:] = 12
print(arr_slice)
print(arr)

l'array és: [0 1 2 3 4 5 6 7 8 9]
l'element 2: 2
secció de l'array: [5 6 7]
[12 12 12]
[ 0  1  2  3  4 12 12 12  8  9]


In [97]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Seleccionar una fila
print(arr2d[0])

# Seleccionar un element. [fila, columna]
print(arr2d[1, 0])
# print(arr2d[1][0]) equivalent

# Seleccionar files i columnes concretes
print(arr2d[:, 2]) # de totes les files, la columna 2
print(arr2d[:2, 1:]) # files 0 i 1 i columnes 1 i 2


[1 2 3]
4
[3 6 9]
[[2 3]
 [5 6]]


In [99]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Seleccionar una matriu, una profunditat
print(arr3d[0])

# Seleccionar una fila d'una matriu
print(arr3d[0, 1])

# Seleccionar un element [profunditat, fila, columna]
print(arr3d[0, 1, 2])

# Seleccionar files i columnes concretes
print(arr3d[0, : , 0:2]) # De la matriu 0, de totes les files, la columna 0 i 1.

[[1 2 3]
 [4 5 6]]
[4 5 6]
6
[[1 2]
 [4 5]]


## Boolean indexing

- Copies the data into a new array
- These types of operations on two-dimensional data are convenient to do with PANDAS.

In [19]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]) # 1 fila x 7 columnes
data = np.random.randn(7, 4) # 7 files x 4 columnes
print(data)

print(names == "Bob")

# print(data[names == "Bob"]) # Les files que tenen element True, és a dir, corresponen a name Bob
print(data[~(names == "Bob")]) # Les files que tenen element False, és a dir, NO corresponen a name Bob
# print(data[names == "Bob", 3]) # Les files que tenen element True, només la columna 3
# Es poden usar condicions booleanes, com & (and) i | (or)

cond = (names == "Bob") | (names == "Will")
print(cond)
print(data[cond])

# Assignar valors amb boolean arrays
data[data < 0] = 0
print(data)


[[-2.24877612  1.34463917 -0.31275184  1.09728874]
 [-0.37101147  1.06814552  0.35812087 -1.51198406]
 [ 0.88091542  0.80867549 -0.24648401 -0.40142589]
 [-0.22785245  0.45574731 -0.18669199  1.92918646]
 [-0.14211232 -1.87673285  0.5517759   0.31644977]
 [ 0.40997769 -0.57666088 -2.22441673  0.58946659]
 [ 0.13141444  1.55849358 -0.09934236 -0.63033757]]
[ True False False  True False False False]
[[-0.37101147  1.06814552  0.35812087 -1.51198406]
 [ 0.88091542  0.80867549 -0.24648401 -0.40142589]
 [-0.14211232 -1.87673285  0.5517759   0.31644977]
 [ 0.40997769 -0.57666088 -2.22441673  0.58946659]
 [ 0.13141444  1.55849358 -0.09934236 -0.63033757]]
[ True False  True  True  True False False]
[[-2.24877612  1.34463917 -0.31275184  1.09728874]
 [ 0.88091542  0.80867549 -0.24648401 -0.40142589]
 [-0.22785245  0.45574731 -0.18669199  1.92918646]
 [-0.14211232 -1.87673285  0.5517759   0.31644977]]
[[0.         1.34463917 0.         1.09728874]
 [0.         1.06814552 0.35812087 0.        ]

# Fancy indexing

- indexing using integer arrays
- Copies the data into a new array

In [25]:
arr = np.empty((8, 4))
for i in range(8) :
    arr[i] = i
print(arr)

# Seleccionar i mostrar files en cert ordre

arr[[4, 3, 0]] # fila 4, fila 3, fila 0
arr[[-3, -5]] # fila 5, fila 3

arr2 = np.arange(32).reshape((8,4))
print(arr2)
arr2[[1, 5, 7],[0, 3, 1]] # Elements (1,0), (5,3) i (7,1)
arr2[[1, 5, 7]][ : , [0, 3, 1]] # Les files 1, 5 i 7 i les columnes d'aquestes en ordre 0, 3 i 1.

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29]])

# Transposing arrays and swapping axes

- Returns a view, not a copy. La dimensió de l'array original no es modifica (transposar només és una manera diferent de visualitzar l'array), però si del transposat canviem un element, es canviarà també en l'array original!

In [62]:
arr = np.arange(15).reshape((3,5))

tr = arr.T # transposar la matriu, per array de fins dimensió 2
print(tr)

# Si modifico un element de tr es canviarà també en arr. 
tr[0, 0] = 6
print(tr)
print(arr) # Segueix sent 3x5 però l'element 0,0 és ara un 6.

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 6  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 6  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [64]:
# per dimensions > 2

arr3 = np.arange(16).reshape((2, 2, 4))

print(arr3.transpose((1, 0, 2))) # element (prof,fila,col) passa a posició (fila,prof,col). 
# per intercanviar dos axis, és equivalent
# arr3.swapaxes(0,1)

"""
1,1,1 passa a 1,1,1
...
1,1,4 passa a 1,1,4
1,2,1 passa a 2,1,1
...
1,2,4 passa a 2,1,4
2,1,1 passa a 1,2,1
...
2,1,4 passa a 1,2,4
2,2,1 passa a 2,2,1
...
2,2,4 passa a 2,2,4
"""

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


'\n1,1,1 passa a 1,1,1\n...\n1,1,4 passa a 1,1,4\n1,2,1 passa a 2,1,1\n...\n1,2,4 passa a 2,1,4\n2,1,1 passa a 1,2,1\n...\n2,1,4 passa a 1,2,4\n2,2,1 passa a 2,2,1\n...\n2,2,4 passa a 2,2,4\n'

## Universal functions

In [49]:
# EXEMPLES
x = np.arange(8)

# unary ufuncs
np.exp(x) # e elevat a element de x
np.sqrt(x) # arrel d'element de x

# binary ufuncs

y = np.arange(9, 17)

print(np.add(x,y)) 
# equivalent: print(x + y)

print(np.maximum(x,y))

[ 9 11 13 15 17 19 21 23]
[ 9 10 11 12 13 14 15 16]
