**Índex**

ndarray - N-dimensional array object

1. [Característiques: dimension, shape, dtype](#id1)

2. [Creació](#id2)

3. [Operacions amb arrays (vectorization)](#id3)

4. [Indexing and slicing](#id4)

5. [Boolean indexing](#id5)

6. [Fancy indexing](#id6)

7. [Transposing arrays and swapping axes](#id7)

8. [Universal functions](#id8)

9. [Conditional logic as array operations](#id9)

10. [Methods any/all](#id10)

11. [Mathematical and Statistical methods](#id11)

12. [Sorting](#id12)

13. [Set operations for 1D arrays](#id13)

14. [File input and output with arrays](#id14)

15. [Lineal Algebra](#id15)


In [2]:
import numpy as np

# ndarray - N-dimensional array object

- All of the elements must be the same type

<div id='id1' />

## Característiques: dimension, shape, dtype

In [7]:
# De llista a array

llista = [[[1, 2, 3, 4], [5.4, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]

arr = np.array(llista)

print(arr) # tots seran floats perquè n'hi havia un i tots han de tenir el mateix type

print(arr.ndim) # 3 dimensions. Profunditat, files, columnes
print(arr.shape) # 2 matrius Profunditat, 2 files, 4 columnes
print(arr.dtype) # són floats

# Forçar el type dels elements
arr2 = np.array(llista, dtype=np.int64) # Els decimals els trunca
print(arr2)

# Convertir el tipus d'un array. Sempre crea un NOU array, una còpia de l'anterior canviant el tipus.
arr22 = arr.astype(np.int64) # De arr type float a arr22 type int
print(arr22)

[[[ 1.   2.   3.   4. ]
  [ 5.4  6.   7.   8. ]]

 [[ 9.  10.  11.  12. ]
  [13.  14.  15.  16. ]]]
3
(2, 2, 4)
float64
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


<div id='id2' />

## Creació

In [5]:
# De llista a array
llista = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr = np.array(llista)
print(arr)

# Donats uns valors
arr2 = np.array([[7, 1, 9], [10, 11, 12]])
print(arr2)

# Crear array amb valors random seguint distribució normal mean 0, standard deviation 1.
data = np.random.randn(2,3)
print(data)
# np.random.binomial
# np.random.uniform
# np.random.randint - draw random integers from a given low-to-high (no inclòs) range
# ...

# Crear array de zeros o uns
zeros = np.zeros(3) # 1 fila, 3 columnes
print(zeros)
uns = np.ones((1,2))
print(uns)

# Crear array amb valors qualsevol, sense inicialitzar. De vegades són zeros, a vegades no.
garbage = np.empty((2,1,3))
print(garbage)

# Crear array similar a funció range
num = np.arange(15)
print(num)
num2 = np.arange(8).reshape((4, 2)) # del 0 al 7 en 4 files i 2 columnes.
print(num2)

identitat = np.identity(3) # matriu identitat 3x3
print(identitat)

[[1 2 3 4]
 [5 6 7 8]]
[[ 7  1  9]
 [10 11 12]]
[[ 0.01471052 -0.59431224  0.58181148]
 [ 0.25250922 -1.287315    0.1382078 ]]
[0. 0. 0.]
[[1. 1.]]
[[[0.01471052 0.59431224 0.58181148]]

 [[0.25250922 1.287315   0.1382078 ]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<div id='id3' />

## Operacions amb arrays (vectorization)

- Com operacions amb matrius.
- Cal que tinguin la mateixa dimensió.
- Cuando operamos entre arrays con dimensiones diferentes, siempre y cuando se cumplan ciertas restricciones en tamaños de filas y/o columnas, lo que se produce es un «broadcasting» (o difusión) de los valores.

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 1, 9], [10, 11, 12]])

print(arr + arr2)
print(arr - arr)
print(arr ** 2)
print(1/arr)
print(arr2 > arr)

[[ 8  3 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ True False  True]
 [ True  True  True]]


In [54]:
# broadcasting

m23 = np.array([[9, 8, 1], [7, 6, 7]])
m13 = np.array([2, 3, 6])
m21 = np.array([[1], [6]])

print(m23 + m13) # Suma la fila de m13 a les dues files de m23
print(m23 + m21) # Suma la columna de m21 a les 3 columnes de m23

[[11 11  7]
 [ 9  9 13]]
[[10  9  2]
 [13 12 13]]


<div id='id4' />

## Indexing and slicing

- Array slices are VIEWS on the original array. This means that data is not copied, and ANY MODIFICATIONS TO THE VIEW WILL BE REFLECTED IN THE SOURCE ARRAY.

In [79]:
arr = np.arange(10)
print("l'array és:", arr)

# Seleccionar un element
print("l'element 2:", arr[2])

# Seleccionar un slice
print("secció de l'array:", arr[5:8]) # l'element 5, 6 i 7, començant a contar per 0.

# Modificar elements
arr_slice = arr[5:8]
arr_slice[:] = 12
print(arr_slice)
print(arr)

l'array és: [0 1 2 3 4 5 6 7 8 9]
l'element 2: 2
secció de l'array: [5 6 7]
[12 12 12]
[ 0  1  2  3  4 12 12 12  8  9]


In [97]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Seleccionar una fila
print(arr2d[0])

# Seleccionar un element. [fila, columna]
print(arr2d[1, 0])
# print(arr2d[1][0]) equivalent

# Seleccionar files i columnes concretes
print(arr2d[:, 2]) # de totes les files, la columna 2
print(arr2d[:2, 1:]) # files 0 i 1 i columnes 1 i 2


[1 2 3]
4
[3 6 9]
[[2 3]
 [5 6]]


In [99]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Seleccionar una matriu, una profunditat
print(arr3d[0])

# Seleccionar una fila d'una matriu
print(arr3d[0, 1])

# Seleccionar un element [profunditat, fila, columna]
print(arr3d[0, 1, 2])

# Seleccionar files i columnes concretes
print(arr3d[0, : , 0:2]) # De la matriu 0, de totes les files, la columna 0 i 1.

[[1 2 3]
 [4 5 6]]
[4 5 6]
6
[[1 2]
 [4 5]]


<div id='id5' />

## Boolean indexing

- Copies the data into a new array
- These types of operations on two-dimensional data are convenient to do with PANDAS.

In [19]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]) # 1 fila x 7 columnes
data = np.random.randn(7, 4) # 7 files x 4 columnes
print(data)

print(names == "Bob")

# print(data[names == "Bob"]) # Les files que tenen element True, és a dir, corresponen a name Bob
print(data[~(names == "Bob")]) # Les files que tenen element False, és a dir, NO corresponen a name Bob
# print(data[names == "Bob", 3]) # Les files que tenen element True, només la columna 3
# Es poden usar condicions booleanes, com & (and) i | (or)

cond = (names == "Bob") | (names == "Will")
print(cond)
print(data[cond])

# Assignar valors amb boolean arrays
data[data < 0] = 0
print(data)


[[-2.24877612  1.34463917 -0.31275184  1.09728874]
 [-0.37101147  1.06814552  0.35812087 -1.51198406]
 [ 0.88091542  0.80867549 -0.24648401 -0.40142589]
 [-0.22785245  0.45574731 -0.18669199  1.92918646]
 [-0.14211232 -1.87673285  0.5517759   0.31644977]
 [ 0.40997769 -0.57666088 -2.22441673  0.58946659]
 [ 0.13141444  1.55849358 -0.09934236 -0.63033757]]
[ True False False  True False False False]
[[-0.37101147  1.06814552  0.35812087 -1.51198406]
 [ 0.88091542  0.80867549 -0.24648401 -0.40142589]
 [-0.14211232 -1.87673285  0.5517759   0.31644977]
 [ 0.40997769 -0.57666088 -2.22441673  0.58946659]
 [ 0.13141444  1.55849358 -0.09934236 -0.63033757]]
[ True False  True  True  True False False]
[[-2.24877612  1.34463917 -0.31275184  1.09728874]
 [ 0.88091542  0.80867549 -0.24648401 -0.40142589]
 [-0.22785245  0.45574731 -0.18669199  1.92918646]
 [-0.14211232 -1.87673285  0.5517759   0.31644977]]
[[0.         1.34463917 0.         1.09728874]
 [0.         1.06814552 0.35812087 0.        ]

<div id='id6' />

## Fancy indexing

- indexing using integer arrays
- Copies the data into a new array

In [25]:
arr = np.empty((8, 4))
for i in range(8) :
    arr[i] = i
print(arr)

# Seleccionar i mostrar files en cert ordre

arr[[4, 3, 0]] # fila 4, fila 3, fila 0
arr[[-3, -5]] # fila 5, fila 3

arr2 = np.arange(32).reshape((8,4))
print(arr2)
arr2[[1, 5, 7],[0, 3, 1]] # Elements (1,0), (5,3) i (7,1)
arr2[[1, 5, 7]][ : , [0, 3, 1]] # Les files 1, 5 i 7 i les columnes d'aquestes en ordre 0, 3 i 1.

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5],
       [20, 23, 21],
       [28, 31, 29]])

<div id='id7' />

## Transposing arrays and swapping axes

- Returns a view, not a copy. La dimensió de l'array original no es modifica (transposar només és una manera diferent de visualitzar l'array), però si del transposat canviem un element, es canviarà també en l'array original!

In [62]:
arr = np.arange(15).reshape((3,5))

tr = arr.T # transposar la matriu, per array de fins dimensió 2
print(tr)

# Si modifico un element de tr es canviarà també en arr. 
tr[0, 0] = 6
print(tr)
print(arr) # Segueix sent 3x5 però l'element 0,0 és ara un 6.

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 6  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 6  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [64]:
# per dimensions > 2

arr3 = np.arange(16).reshape((2, 2, 4))

print(arr3.transpose((1, 0, 2))) # element (prof,fila,col) passa a posició (fila,prof,col). 
# per intercanviar dos axis, és equivalent
# arr3.swapaxes(0,1)

"""
1,1,1 passa a 1,1,1
...
1,1,4 passa a 1,1,4
1,2,1 passa a 2,1,1
...
1,2,4 passa a 2,1,4
2,1,1 passa a 1,2,1
...
2,1,4 passa a 1,2,4
2,2,1 passa a 2,2,1
...
2,2,4 passa a 2,2,4
"""

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


'\n1,1,1 passa a 1,1,1\n...\n1,1,4 passa a 1,1,4\n1,2,1 passa a 2,1,1\n...\n1,2,4 passa a 2,1,4\n2,1,1 passa a 1,2,1\n...\n2,1,4 passa a 1,2,4\n2,2,1 passa a 2,2,1\n...\n2,2,4 passa a 2,2,4\n'

<div id='id8' />

## Universal functions

In [49]:
# EXEMPLES
x = np.arange(8)

# unary ufuncs
np.exp(x) # e elevat a element de x
np.sqrt(x) # arrel d'element de x

# binary ufuncs

y = np.arange(9, 17)

print(np.add(x,y)) 
# equivalent: print(x + y)

print(np.maximum(x,y))

[ 9 11 13 15 17 19 21 23]
[ 9 10 11 12 13 14 15 16]


In [6]:
# AVALUAR UNA FUNCIÓ EN DOS ARRAYS

# Generem dos arrays que corresponen a les coordenades (x,y) del pla amb eix x i y entre -5 i 5
points = np.arange(-5, 5, 0.01) # 1000 punts equiespaiats

xs, ys = np.meshgrid(points, points) # xs coordenades x dels punts, ys coordenades y dels punts del pla cartesià.

# Avaluem la funció f(x,y)=\sqrt(x^2 + y^2)

z = np.sqrt(xs**2 + ys**2)

print(z)

[[7.07106781 7.06400028 7.05693985 ... 7.04988652 7.05693985 7.06400028]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 ...
 [7.04988652 7.04279774 7.03571603 ... 7.0286414  7.03571603 7.04279774]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]]


<div id='id9' />

## Conditional logic as array operations

- np.where function is a vectorized version of the ternary expression  x if condition else y.

In [15]:
arr = np.random.randn(4, 4)
print(arr)

arr2 = np.where(arr > 0, 2, -2)  # condició, if, else
print(arr2)

arr22 = np.where(arr > 0, 2, arr) # Si no és més gran que 0, deixar com està.
print(arr22)

[[-0.59486748  0.21922459 -0.87501093  0.00368342]
 [-0.56141373 -1.29257504  1.86911838  0.60557576]
 [ 1.40959676  0.74853501 -0.89380565  0.31291333]
 [ 0.89920303 -1.23998449 -0.01933667  1.02671039]]
[[-2  2 -2  2]
 [-2 -2  2  2]
 [ 2  2 -2  2]
 [ 2 -2 -2  2]]
[[-0.59486748  2.         -0.87501093  2.        ]
 [-0.56141373 -1.29257504  2.          2.        ]
 [ 2.          2.         -0.89380565  2.        ]
 [ 2.         -1.23998449 -0.01933667  2.        ]]


<div id='id10' />

## Methods any/all

- "any" tests whether one or more values in an array is True.
    - Per NO-BOOLEAN, testeja si hi ha algun element NO NUL.
- "all" checks if every value is True. 
    - Per NO-BOOLEAN, testeja si tots els elements són NO NULS.

In [37]:
bools = np.array([False, True, False, False])

bools.any() #True
bools.all() #False

zeros = np.array([1, 0, 0, 0, 0])

zeros.any() #True
zeros.all() #False

False

<div id='id11' />

## Mathematical and Statistical methods

In [18]:
arr = np.random.randn(5, 4)
print(arr)

print("Mitjana de tots els elements:", arr.mean())
print("Suma de tots els elements:", arr.sum())
print("Mitjana del elements de les files, recorrem saltant de columna:", arr.mean(axis=1))
print("Suma dels elements de les columnes, recorrem saltant de fila:", arr.sum(axis=0))

[[-0.23209153 -0.03163017 -1.08887258 -1.74197476]
 [ 0.78710677  1.02009365  1.37570389 -1.78598153]
 [-0.62316509  0.66035936 -2.25087597 -0.11476684]
 [-0.08794676  1.96278232  0.37908568  0.92386256]
 [ 0.91025451 -2.27081926 -1.14859974 -1.95709939]]
Mitjana de tots els elements: -0.2657287436352105
Suma de tots els elements: -5.31457487270421
Mitjana del elements de les files, recorrem saltant de columna: [-0.77364226  0.3492307  -0.58211213  0.79444595 -1.11656597]
Suma dels elements de les columnes, recorrem saltant de fila: [ 0.75415789  1.3407859  -2.73355872 -4.67595995]


<div id='id12' />

## Sorting

In [41]:
arr = np.random.randn(5, 3)
print(arr)

arr.sort(1) # Ordena els elements de les files de petit a gran, recorrem saltant de columna. Si l'array és 1D no cal indicar axis. Modifica l'array original.
print(arr)

[[-0.86528384  0.40987454  1.76522468]
 [-0.1081927  -0.58914139 -0.7162941 ]
 [ 0.11417114  2.07024884 -0.75445289]
 [ 1.98949629  0.0294386  -2.01019775]
 [ 0.46967304  0.54633934 -0.66127514]]
[[-0.86528384  0.40987454  1.76522468]
 [-0.7162941  -0.58914139 -0.1081927 ]
 [-0.75445289  0.11417114  2.07024884]
 [-2.01019775  0.0294386   1.98949629]
 [-0.66127514  0.46967304  0.54633934]]


<div id='id13' />

## Set operations for 1D arrays

- unique - retorna elements únics de l'array
- in1d - retorna true/false si cada un dels valors de l'array és del llistat demanat

In [50]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

print(np.unique(names))

print(np.in1d(names, ["James"]))
print(np.in1d(names, ["James", "Joe"]))
print(np.in1d(names, ["James", "Joe", "Bob"]))

['Bob' 'Joe' 'Will']
[False False False False False False False]
[False  True False False False  True  True]
[ True  True False  True False  True  True]


<div id='id14' />

## File input and output with arrays

- Most users will prefer pandas and other tools for loading text or tabular data

<div id='id15' />

## Lineal Algebra

In [59]:
from numpy.linalg import inv, det, solve # PAQUET LINEAL ALGEBRA DE NUMPY amb operacions tipus diagonalitzar matrius, multiplicar, la traça, determinants, inversa, eigenvalues, resoldre equació matricial senzilla...

a = np.array([[1, 2, 3], [4, 5, 6]]) # 2x3
c = np.array([[1, 2, 8], [3, 4, 5], [5, 6, 7]]) # 3x3

print(a.dot(c)) # 2x3 · 3x3 = 2x3
# equivalent np.dot(x,y)

print(inv(c))
print(det(c))

b = np.array([[1, 2], [4, 5], [8, 9]])
solve(c, b) # solve AX=B, A: 3x3, X: 3x2 , B: 3x2 La matriu A ha de ser QUADRADA

[[22 28 39]
 [49 64 99]]
[[ 0.2 -3.4  2.2]
 [-0.4  3.3 -1.9]
 [ 0.2 -0.4  0.2]]
-9.999999999999984


array([[ 4.2,  3.2],
       [-2.4, -1.4],
       [ 0.2,  0.2]])